# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-covidhackathon-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::libdeflate=1.3
  - conda-forge::r-base=3.6.1
  - conda-forge::r-markdown=1.1
# TODO nf-core: Add required software dependencies here
  - bioconda::hisat2=2.2.0
  - bioconda::fastqc=0.11.8
  - bioconda::gffcompare=0.11.2
  - bioconda::htslib=1.10.2
  - bioconda::picard=2.22.2
  - bioconda::samtools=0.1.19
  - bioconda::sortmerna=2.1b
  - bioconda::STAR=2.7.3a
  - bioconda::stringtie=2.1.1
  - bioconda::multiqc=1.8
